MIN_ARGS = 1
MAX_ARGS = 3

MODE_ARG = 0
COLOR_ARG = 1
LEVEL_ARG = 2

SINGLE_ARG_MODES = 0
MULTI_ARG_MODES = 1

INFO_MODE = "Info"
TEST_MODE = "Test"
SINGLE_MODE = "Single"

ARG_MODES = [[INFO_MODE, TEST_MODE, "Clear", "Spectrum", "Bespoke", "Breathing"],
             [SINGLE_MODE]]

RGB_DEVICE_COUNT = 3
